### ISSUE TITLE
(Possible) Bug: cinchlog.h gets included from multiple locations

### ISSUE THREAD

**Issue by timmah** [laristra/flecsi-sp#33]
## Symptom
A flecsi-sp build fails because functions and macros in cinchlog.h are defined multiple times.
 
## Proposed Diagnosis
The cinchlog.h header gets included from several places. A flecsi-sp header includes it from the version of cinch that ships as a flecsi-sp submodule. A flecsi header includes it from the version installed when flecsi is built and installed. 

As long as cinchlog.h used traditional include guards (and there was no variation between the versions!) this was not an issue. When cinchlog.h is changed to use #pragma once, these are seen as different files (because they are different files) and multiple definitions ensue.

## Possible solutions:
1. Don't make cinch a submodule of flecsi-sp
2. Make flecsi a submodule of flecsi-sp
3. Move cinch logging out of cinch
3. Don't use #pragma once in cinchlog.h (or anywhere else that it is a problem, but everywhere else do use it)

## Weak point in submodules + cinch
This has revealed a problem with the submodule+cinch way of life--how do you keep all the instances of cinch submodules at the same version in libristra, flecsi, flecsi-sp, flecsale, etc.

**Comment by cferenba** [comment]
@timmah : You've stumbled onto one of the corner cases where the correct behavior of `#pragma once` can't be well defined.  As I understand it, this sort of thing is why `#pragma once` isn't in the standard, and probably never will be.

**Comment by cmsquared** [comment]
Solution 2 would actually help solve Issue #34 .

**Comment by cmsquared** [comment]
Should be fixed in libristra/cinch#164 .  Perhaps we should cut a new point release of cinch for other packages to include...
