### ISSUE TITLE
Which version of FleCSI is supported?

### ISSUE THREAD

**Issue by cmsquared** [laristra/flecsi-sp#34]
There doesn't appear to be a good way (as best I can tell) to determine which version of the FleCSI API we are using here.  I'm not entirely sure what the solution is, as the build doesn't require a specific version of FleCSI, just that it is found.  Obviously things fail to compile if the API is incorrect, but I have no idea to what hash/version I need to update FleCSI.

Any thoughts?  Maybe more of a project-level discussion, @cferenba @ddaniel ?

**Comment by cferenba** [comment]
My best suggestion right now is to see which Flecsi version is used by Flecsale (which also uses Flecsi-SP), and try that.  You're right that we need a better long-term solution.

**Comment by cmsquared** [comment]
Well, that would work if I always wanted to be tied to the versions used in FleCSALE.  I want to update the flecsi-sp submodule within symphony to the latest to take advantage of some recent changes.  So, I need to update the flecsi submodule there too, so that it is consistent with the updated flecsi-sp.  FleCSALE is using a version from May.

**Comment by charest** [comment]
FleCSI-SP does not use FleCSI as a submodule.

**Comment by cmsquared** [comment]
Right, but FleCSI-SP uses methods from FleCSI, and if the API has changed to be inconsistent, then we need to update the FleCSI we are using.

**Comment by charest** [comment]
closed due to inactivity
