### ISSUE TITLE
flecsi-sp broken with refactored flecsi master

### ISSUE THREAD

**Issue by junghans** [laristra/flecsi-sp#9]

**Comment by ollielo** [comment]
@junghans ,

Which build on the Travis are you talking about?

I tried to build flecsi/master and flecsi-sp/master for serial. They worked.

**Comment by junghans** [comment]
See: https://travis-ci.org/laristra/flecsi-sp/builds/246815706

Please remember that, currently there is no serial version of flecsi anymore.

**Comment by charest** [comment]
Pretty sure their is not much use trying to get flecsi-sp to build against the master branch of flecsi right now.  All of the burton specialization won't build.

**Comment by cmsquared** [comment]
Is this still an issue?
